### ISSUE TITLE
Main structure

### ISSUE THREAD

**Issue by AAPPHH** [AAPPHH/Particle_Life_Simulator#21]
The task is to create a visualization of a numpy array using VisPy, where a single particle moves randomly across the array. The visualization should include the following:

1. Array Representation: The values in the numpy array should be visually represented, for example, with a color map or intensity gradients.
2. Random Particle Movement: A single particle should move randomly on the array, with no interaction with the array values or other particles.
3. Basic Animation: The particle's random movement should be animated in real time, demonstrating its changing position.

This serves as a foundational step for building more advanced features, such as multiple particles or interactive elements.

**Comment by Fouad-G** [comment]
I tried VisPy, Pygame, and DearPyGui for the task. Based on my experience, Pygame is quite useful if we aim to implement a basic particle simulator. It is sufficient for rendering about 300 particles in real-time (with room for optimization, but that’s what I managed yesterday). However, if you are looking for the best performance, the DearPyGui library offers greater efficiency and scalability.

As for the example you requested, I will work on it and provide a demonstration using Pygame. This should effectively illustrate the single-particle random movement and basic animation that you're looking for. Let me know if you'd like further insights or assistance with implementation.
